 pipeline{
    agent{
        label "master"
    }
    tools { nodejs "Default" }
    stages{
        stage("Prepare Environment"){
            steps{
                sh "node --version"
                sh "npm install"
            }
        }
        stage("Test Code"){
            steps{
                sh "npm run prodtest" 
            }
        }
        stage("SonarCloud Report"){
            steps{
                echo "TODO"
            }
        }
        stage("Build Code"){
            steps{
                sh "REACT_APP_API_URL=http://ec2-34-204-205-63.compute-1.amazonaws.com/rev-overflow-service npm run build"
            }
        }
        stage("Build Docker Image"){
            when{
                branch "master"
            }
            steps{
                sh "sudo chmod -R 755 ./build"
                sh "docker image build -t rev-overflow-frontend:canada-latest ."
            }
        }
        stage("Kill Old Container"){
            when{
                branch "master"
            }
            steps{
                script{
                    try{
                        sh"docker stop \$(docker ps -a -q --filter \"name=rev-overflow-frontend\")"
                        sh"docker rm \$(docker ps -a -q --filter \"name=rev-overflow-frontend\")"
                    } 
                    catch(e){
                    } 
                } 
            }
        }
        stage("Run New Container"){
            when{
                branch "master"
            }
            steps{
                sh "docker container run -p 80:80 -d --name=rev-overflow-frontend rev-overflow-frontend:canada-latest"
            }
        }
    }
    post{
        always{
           cleanWs()
        }
        success{
            echo "SUCCESS"
        }
        failure{
            echo "FAILURE"
        }
    }
} 